//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoGeneratedTests
{
    using System;
    using System.Linq;
    using System.ComponentModel;
    
    
    public class weeaboo
    {
        
		[DefaultValue("20120205-1000-1")]
		public System.Nullable<string> docID { get; set; }

    }
}
